version: "3.3"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on: 
      - mongo
      - redis
  mongo:
    image: mongo:latest
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes: 
      - mongo:/data/db
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
volumes: 
  mongo: